services:
  - type: web
    name: ROYAL-BOT-263
    env: node
    branch: main
    repo: https://github.com/partso/ROYAL-BOT-263.git
    buildCommand: yarn install
    startCommand: node ./index.js
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MODE
        sync: false
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
